backend:
  name: git-gateway
  branch: master
media_folder: "src/site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/site/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "post" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/blog.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
