backend:
  name: git-gateway
  branch: master
media_folder: "src/site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    description: "Blog posts for the site."
    folder: "src/site/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "post" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    label_singular: "page"
    description: "Pages that aren't blog posts"
    folder: "src/site/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/page.njk",
        }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
